services:
  postgres:
    image: postgres:17
    container_name: room-reservation-db
    environment:
      POSTGRES_DB: room_reservation
      POSTGRES_USER: room_reservation
      POSTGRES_PASSWORD: room_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: